#!/bin/bash
# build.sh — build and install vk_flip_meter layer (v2.5)
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
INSTALL_PREFIX="${1:-/usr/local}"
NATIVE_BUILD="${FLM_NATIVE_BUILD:-OFF}"

echo "==> Building vk_flip_meter (v2.5)"
echo "    Prefix: $INSTALL_PREFIX"
if [ "$NATIVE_BUILD" = "ON" ]; then
    echo "    Native build: ON (-O3 -march=native -mtune=native -flto, runs on this machine only)"
fi
echo ""

# Vulkan header check
if [ ! -f /usr/include/vulkan/vulkan.h ] && \
   [ ! -f /usr/local/include/vulkan/vulkan.h ]; then
    echo "ERROR: Vulkan headers not found."
    echo "       Gentoo: sudo emerge -av media-libs/vulkan-loader"
    exit 1
fi

if ! find /usr/include /usr/local/include -name "vk_layer.h" 2>/dev/null | grep -q .; then
    echo "ERROR: vk_layer.h not found."
    echo "       Gentoo: sudo emerge -av media-libs/vulkan-layers"
    exit 1
fi

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Prefer Ninja when available
if command -v ninja >/dev/null 2>&1; then
    GENERATOR="Ninja"
    BUILD_CMD="ninja -j$(nproc)"
    INSTALL_CMD="sudo ninja install"
else
    echo "==> ninja not found, using Unix Makefiles"
    GENERATOR="Unix Makefiles"
    BUILD_CMD="make -j$(nproc)"
    INSTALL_CMD="sudo make install"
fi

cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
    -DCMAKE_INSTALL_LIBDIR="lib64" \
    -DFLM_NATIVE_BUILD="$NATIVE_BUILD" \
    -G "$GENERATOR"

$BUILD_CMD

echo ""
echo "==> Installing (may need sudo)"
$INSTALL_CMD

# [FIX-52] The manifest is now generated by CMake configure_file with the
# correct path+version; no post-install sed patching needed.

echo ""
echo "==> Install complete. Verify:"
echo "    vulkaninfo --summary | grep -i flip_meter"
echo ""
echo "============================================================"
echo " QUICK VERIFICATION (2-second proof the layer is active)"
echo "============================================================"
echo ""
echo "  # LIMITER mode: MangoHud should show a flat 60 FPS line."
echo "  # Does NOT require presentWait, works on every driver."
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=limiter FLM_TARGET_FPS=60 mangohud %command%"
echo ""
echo "============================================================"
echo " USAGE"
echo "============================================================"
echo ""
echo "  # Automatic (PACER if presentWait is available, else LIMITER when fps is set):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 %command%"
echo ""
echo "  # Force PACER (frametime correction on a VRR panel):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=present %command%"
echo ""
echo "  # FPS cap (limiter, the most reliably visible effect):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=limiter FLM_TARGET_FPS=120 %command%"
echo ""
echo "  # MFG autodetect (detect the multiplier automatically):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MFG_MULTIPLIER=0 %command%"
echo ""
echo "  # MFG 3x manual + target fps + debug log:"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MFG_MULTIPLIER=3 FLM_TARGET_FPS=60 FLM_LOG_LEVEL=DEBUG %command%"
echo ""
echo "  # How far before the flip to release the present gate (ns, default 1ms):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=present FLM_PRESENT_LEAD_NS=1500000 %command%"
echo ""
echo "  # Choose the gate point (present|acquire|both, default present):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_PACE_POINT=acquire %command%"
echo ""
echo "  # Spin window — 20-25us is enough on an RTX 4080M (0 = pure sleep, min CPU):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_SPIN_NS=20000 %command%"
echo ""
echo "  # Pin the measurement thread to specific cores (CCD isolation):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MEASURE_CPU=0-3 %command%"
echo ""
echo "  # Realtime priority + log file:"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_LOG_LEVEL=INFO FLM_LOG_FILE=/tmp/flm.log FLM_RT_PRIORITY=40 %command%"
echo ""
echo "  # Drift tolerance (ns, 0 = auto iv/4):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_DRIFT_TOLERANCE_NS=2000000 %command%"
echo ""
echo "  # Summary stats log every 5 seconds:"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_LOG_LEVEL=INFO FLM_STATS=1 %command%"
echo ""
echo "============================================================"
echo " A/B TEST (placebo or not — objective proof)"
echo "============================================================"
echo ""
echo "  # Run the same scene twice, compare the CSVs:"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=off     FLM_CSV=/tmp/off.csv %command%"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=present FLM_CSV=/tmp/on.csv  %command%"
echo "  # on.csv should show lower interval stddev + p99, higher 1% low."
echo ""
echo "============================================================"
echo " LIVE TUNING (without closing the game)"
echo "============================================================"
echo ""
echo "  # Live tuning works through a config FILE (a running process's"
echo "  # environment cannot be changed externally). Start the game with FLM_CONFIG:"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_CONFIG=/tmp/flm.conf %command%"
echo ""
echo "  # Then edit the file (KEY=VALUE lines) and send SIGUSR1:"
echo "  echo 'FLM_TARGET_FPS=90' > /tmp/flm.conf"
echo "  echo 'FLM_MODE=present'  >> /tmp/flm.conf"
echo "  kill -SIGUSR1 \$(pgrep -f game_name)"
echo ""
echo "  # Build with native optimizations (this machine only, not portable):"
echo "  FLM_NATIVE_BUILD=ON ./build.sh"
echo ""
